# Generated by Django 3.0.7 on 2020-06-17 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qna', '0002_auto_20200613_1106'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='correct',
            field=models.BooleanField(default=False),
        ),
    ]
